spring:
  application:
    name : cdri-book
  datasource:
    cdri-books:
      hikari:
        jdbc-url: jdbc:mysql://192.168.0.7:63306/cdri_books
        username: root
        password: pass
  jpa:
    show-sql: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
